### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cantecim**
Add action usage example in socketAuthorize

### CODE REVIEW

**Comment by cantecim** [comment]
Hello @tiaod kindly can you merge this?

**Comment by tiaod** [comment]
@cantecim Wait, where is the `ctx` come from?

**Comment by cantecim** [comment]
@tiaod Oh sorry, forgot that was in hurry, now it looks good

**Comment by tiaod** [comment]
I think maybe it's better to use `async/await`? 🤔 
I updated your example, thanks for help

**Pull request merged**
